server:
  port: 9093

spring:

  # Data Source
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
    username: root
    password: 124578
    driver-class-name: com.mysql.jdbc.Driver
  
  # Redis  
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 
    pool:
      max-active: 8  # 连接池最大连接数
      max-wait: -1   # 最大阻塞等待时间
      max-idle: 8    # 最大空闲连接数
      min-idle: 0    # 最小空闲连接数
    timeout: 0       # 连接超时时间(ms)
    
# My Batis
mybatis:
  typeAliasesPackage: com.sgh.demo.domain
  mapperLocations: classpath:mapper/*.xml 
