server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
    username: root
    password: 124578
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.sgh.demo.domain
  mapperLocations: classpath:mapper/*.xml 